import os
import json
import unittest
import pandas as pd

from agent.intelligent_data_assessment import profile_dataframe, analyze_dataset_quality, load_dq_thresholds
from agent.etl_pipeline.planner import build_etl_plan
from agent.etl_pipeline.sql_codegen import generate_sql_etl
from agent.etl_pipeline.validate_sql import validate_sql_basic
from agent.etl_pipeline.dq_gate import check_dq_gate
from agent.etl_pipeline.phase_classifier import split_plan_phases

class TestScenarioMatrix(unittest.TestCase):
    def setUp(self):
        self.fixtures_dir = r"c:\Users\ssakesh\Downloads\DHARA-GX\Agent Dhara Backend\tests\etl_scenarios\fixtures"
        self.thresholds = load_dq_thresholds()

    def _load_fixture(self, name: str) -> pd.DataFrame:
        path = os.path.join(self.fixtures_dir, name)
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        return pd.DataFrame(data)

    def _run_pipeline(self, df: pd.DataFrame, dataset_name: str, rules: dict = None) -> dict:
        profile = profile_dataframe(df)
        dq = analyze_dataset_quality(dataset_name, df, profile, self.thresholds, business_rules=rules)
        profile["quality"] = dq
        
        assessment = {
            "datasets": {
                dataset_name: profile
            }
        }
        
        plan = build_etl_plan(
            assessment,
            rules or {},
            engine="sql"
        )
        return {
            "assessment": assessment,
            "plan": plan,
            "dq": dq
        }

    def test_happy_path(self):
        df = self._load_fixture("happy_path.json")
        res = self._run_pipeline(df, "dbo.happy_path")
        
        sql = generate_sql_etl(res["plan"], res["assessment"], dialect="tsql")
        self.assertTrue(len(sql) > 0)
        
        ok, errs = validate_sql_basic(sql)
        self.assertTrue(ok, f"SQL validation failed: {errs}")
        self.assertIn("A", sql) # grade badge should be high since happy path has no issues

    def test_dirty_dates(self):
        df = self._load_fixture("dirty_dates.json")
        res = self._run_pipeline(df, "dbo.dirty_dates")
        
        sql = generate_sql_etl(res["plan"], res["assessment"], dialect="tsql")
        self.assertTrue(len(sql) > 0)
        
        ok, errs = validate_sql_basic(sql)
        self.assertTrue(ok, f"SQL validation failed: {errs}")
        
        # Verify execution order: Normalize empty strings BEFORE reject checks and type parsing.
        # Check against the actual comment text generated by sql_codegen.py.
        self.assertIn("Normalize empty strings to NULL before validation", sql)
        self.assertIn("Quarantine", sql)  # reject/quarantine operations present
        self.assertIn("Post-validation date/type parsing", sql)

    def test_dirty_emails(self):
        df = self._load_fixture("dirty_emails.json")
        res = self._run_pipeline(df, "dbo.dirty_emails")
        sql = generate_sql_etl(res["plan"], res["assessment"], dialect="tsql")
        ok, errs = validate_sql_basic(sql)
        self.assertTrue(ok, errs)

    def test_wide_table(self):
        df = self._load_fixture("wide_table.json")
        res = self._run_pipeline(df, "dbo.wide_table")
        # Check if priority columns was populated
        cols = res["assessment"]["datasets"]["dbo.wide_table"].get("priority_columns", [])
        self.assertTrue(len(cols) > 0)

    def test_null_primary_keys(self):
        df = self._load_fixture("null_primary_keys.json")
        res = self._run_pipeline(df, "dbo.null_pks")
        sql = generate_sql_etl(res["plan"], res["assessment"], dialect="tsql")
        ok, errs = validate_sql_basic(sql)
        self.assertTrue(ok, errs)

    def test_fk_violations(self):
        df = self._load_fixture("fk_violations.json")
        res = self._run_pipeline(df, "dbo.fk_violations")
        sql = generate_sql_etl(res["plan"], res["assessment"], dialect="tsql")
        ok, errs = validate_sql_basic(sql)
        self.assertTrue(ok, errs)

    def test_encoding_issues(self):
        df = self._load_fixture("encoding_issues.json")
        res = self._run_pipeline(df, "dbo.encoding_issues")
        sql = generate_sql_etl(res["plan"], res["assessment"], dialect="tsql")
        ok, errs = validate_sql_basic(sql)
        self.assertTrue(ok, errs)

    def test_scd2_pattern(self):
        df = self._load_fixture("scd2_pattern.json")
        rules = {
            "scd": {
                "dbo.scd2_pattern": {
                    "type": "scd2",
                    "surrogate_key": "customer_sk",
                    "business_keys": ["customer_id"],
                    "valid_from": "valid_from",
                    "valid_to": "valid_to",
                    "is_current": "is_current"
                }
            }
        }
        res = self._run_pipeline(df, "dbo.scd2_pattern", rules=rules)
        sql = generate_sql_etl(res["plan"], res["assessment"], dialect="tsql")
        ok, errs = validate_sql_basic(sql)
        self.assertTrue(ok, errs)
        self.assertIn("SCD Type 2", sql)

    def test_cleanse_only(self):
        df = self._load_fixture("cleanse_only.json")
        res = self._run_pipeline(df, "dbo.cleanse_only")
        
        # Test split phases
        cleanse_plan, transform_plan = split_plan_phases(res["plan"])
        self.assertTrue(len(cleanse_plan.get("datasets", {}).get("dbo.cleanse_only", {}).get("steps", [])) > 0)
        self.assertEqual(len(transform_plan.get("datasets", {}).get("dbo.cleanse_only", {}).get("steps", [])), 0)

    def test_transform_only(self):
        df = self._load_fixture("transform_only.json")
        # Supply business notes that trigger PII hashing steps (transform phase)
        rules = {
            "notes": "hash ssn and credit card columns for privacy compliance"
        }
        res = self._run_pipeline(df, "dbo.transform_only", rules=rules)
        # Mask ssn / ssn hashing is transform phase
        cleanse_plan, transform_plan = split_plan_phases(res["plan"])
        transform_steps = transform_plan.get("datasets", {}).get("dbo.transform_only", {}).get("steps", [])
        self.assertTrue(len(transform_steps) > 0, "Expected transform-phase steps (e.g. hash_phone for SSN/CC masking)")

    def test_mixed_dq_rating(self):
        df = self._load_fixture("mixed_dq_rating.json")
        res = self._run_pipeline(df, "dbo.mixed_dq")
        gate_res = check_dq_gate(res["assessment"], "dbo.mixed_dq", threshold=70.0)
        # mixed dq with high nulls should fall below 70 threshold
        self.assertFalse(gate_res["passed"])

    def test_force_unlock(self):
        df = self._load_fixture("force_unlock.json")
        res = self._run_pipeline(df, "dbo.force_unlock")
        # should fail gate originally
        gate_res = check_dq_gate(res["assessment"], "dbo.force_unlock", threshold=70.0)
        self.assertFalse(gate_res["passed"])
        
        # bypass gate with unlock override flag
        rules = {"force_unlock": ["dbo.force_unlock"]}
        res_unlocked = self._run_pipeline(df, "dbo.force_unlock", rules=rules)
        gate_res_unlocked = check_dq_gate(res_unlocked["assessment"], "dbo.force_unlock", threshold=70.0, force_unlock=True)
        self.assertTrue(gate_res_unlocked["passed"])

    def test_suspicious_zeros(self):
        df = self._load_fixture("suspicious_zeros.json")
        res = self._run_pipeline(df, "dbo.suspicious_zeros")
        sql = generate_sql_etl(res["plan"], res["assessment"], dialect="tsql")
        ok, errs = validate_sql_basic(sql)
        self.assertTrue(ok, errs)

    def test_near_duplicates(self):
        df = self._load_fixture("near_duplicates.json")
        res = self._run_pipeline(df, "dbo.near_duplicates")
        sql = generate_sql_etl(res["plan"], res["assessment"], dialect="tsql")
        ok, errs = validate_sql_basic(sql)
        self.assertTrue(ok, errs)

    def test_multivariate_outliers(self):
        df = self._load_fixture("multivariate_outliers.json")
        res = self._run_pipeline(df, "dbo.multivariate_outliers")
        sql = generate_sql_etl(res["plan"], res["assessment"], dialect="tsql")
        ok, errs = validate_sql_basic(sql)
        self.assertTrue(ok, errs)

    def test_boolean_inconsistency(self):
        df = self._load_fixture("boolean_inconsistency.json")
        res = self._run_pipeline(df, "dbo.boolean_inconsistency")
        sql = generate_sql_etl(res["plan"], res["assessment"], dialect="tsql")
        ok, errs = validate_sql_basic(sql)
        self.assertTrue(ok, errs)

    def test_sentinel_values(self):
        df = self._load_fixture("sentinel_values.json")
        res = self._run_pipeline(df, "dbo.sentinel_values")
        sql = generate_sql_etl(res["plan"], res["assessment"], dialect="tsql")
        ok, errs = validate_sql_basic(sql)
        self.assertTrue(ok, errs)

if __name__ == "__main__":
    unittest.main()
